function rD = rD_fn(q4,q5,q6,rIx,rIy,theta)
%RD_FN
%    RD = RD_FN(Q4,Q5,Q6,RIX,RIY,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Apr-2018 12:50:51

t2 = pi.*(1.0./2.0);
t3 = q4+t2+theta;
t4 = q4+q5+t2+theta;
t5 = sqrt(2.0);
t6 = pi.*(3.0./4.0);
t7 = q4+q5+q6+t6+theta;
rD = [rIx+cos(t3).*(1.3e1./4.0e1)+cos(t4).*(1.3e1./4.0e1)+t5.*cos(t7).*(1.0./1.0e1);rIy-sin(t3).*(1.3e1./4.0e1)-sin(t4).*(1.3e1./4.0e1)-t5.*sin(t7).*(1.0./1.0e1)];
