function rE = rE_fn(q7,q8,rIx,rIy,theta)
%RE_FN
%    RE = RE_FN(Q7,Q8,RIX,RIY,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Apr-2018 12:50:51

t2 = pi.*(1.0./2.0);
t3 = q7+t2+theta;
t4 = q7+q8+t2+theta;
t5 = -t2+theta;
rE = [rIx+cos(t3).*(1.0./4.0)+cos(t4).*(9.0./2.0e1)+cos(t5).*(1.1e1./2.0e1);rIy-sin(t3).*(1.0./4.0)-sin(t4).*(9.0./2.0e1)-sin(t5).*(1.1e1./2.0e1)];
