function rF = rF_fn(q9,q10,rIx,rIy,theta)
%RF_FN
%    RF = RF_FN(Q9,Q10,RIX,RIY,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Apr-2018 12:50:52

t2 = pi.*(1.0./2.0);
t3 = q9+t2+theta;
t4 = q9+q10+t2+theta;
t5 = -t2+theta;
rF = [rIx+cos(t3).*(1.0./4.0)+cos(t4).*(9.0./2.0e1)+cos(t5).*(1.1e1./2.0e1);rIy-sin(t3).*(1.0./4.0)-sin(t4).*(9.0./2.0e1)-sin(t5).*(1.1e1./2.0e1)];
