function rG = rG_fn(q1,q2,rIx,rIy,theta)
%RG_FN
%    RG = RG_FN(Q1,Q2,RIX,RIY,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Apr-2018 12:50:52

t2 = pi.*(1.0./2.0);
t3 = q1+t2+theta;
t4 = q1+q2+t2+theta;
rG = [rIx+cos(t3).*(1.3e1./4.0e1)+cos(t4).*(1.3e1./4.0e1);rIy-sin(t3).*(1.3e1./4.0e1)-sin(t4).*(1.3e1./4.0e1)];
