function rH = rH_fn(q1,rIx,rIy,theta)
%RH_FN
%    RH = RH_FN(Q1,RIX,RIY,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Apr-2018 15:37:15

t2 = pi.*(1.0./2.0);
t3 = q1+t2+theta;
rH = [rIx+cos(t3).*(1.3e1./4.0e1);rIy-sin(t3).*(1.3e1./4.0e1)];
