function rJ = rJ_fn(q4,q5,rIx,rIy,theta)
%RJ_FN
%    RJ = RJ_FN(Q4,Q5,RIX,RIY,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Apr-2018 12:50:52

t2 = pi.*(1.0./2.0);
t3 = q4+t2+theta;
t4 = q4+q5+t2+theta;
rJ = [rIx+cos(t3).*(1.3e1./4.0e1)+cos(t4).*(1.3e1./4.0e1);rIy-sin(t3).*(1.3e1./4.0e1)-sin(t4).*(1.3e1./4.0e1)];
