function rK = rK_fn(q4,rIx,rIy,theta)
%RK_FN
%    RK = RK_FN(Q4,RIX,RIY,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Apr-2018 12:50:52

t2 = pi.*(1.0./2.0);
t3 = q4+t2+theta;
rK = [rIx+cos(t3).*(1.3e1./4.0e1);rIy-sin(t3).*(1.3e1./4.0e1)];
