function rL = rL_fn(rIx,rIy,theta)
%RL_FN
%    RL = RL_FN(RIX,RIY,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Apr-2018 15:37:15

t2 = theta-pi.*(1.0./2.0);
rL = [rIx+cos(t2).*(1.1e1./2.0e1);rIy-sin(t2).*(1.1e1./2.0e1)];
