function rM = rM_fn(q7,rIx,rIy,theta)
%RM_FN
%    RM = RM_FN(Q7,RIX,RIY,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Apr-2018 15:37:15

t2 = pi.*(1.0./2.0);
t3 = q7+t2+theta;
t4 = -t2+theta;
rM = [rIx+cos(t3).*(1.0./4.0)+cos(t4).*(1.1e1./2.0e1);rIy-sin(t3).*(1.0./4.0)-sin(t4).*(1.1e1./2.0e1)];
