function rT = rT_fn(rIx,rIy,theta)
%RT_FN
%    RT = RT_FN(RIX,RIY,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Apr-2018 12:50:52

t2 = theta-pi.*(1.0./2.0);
rT = [rIx+cos(t2).*(7.0./1.0e1);rIy-sin(t2).*(7.0./1.0e1)];
