function V = V_fn(q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,rIy,theta)
%V_FN
%    V = V_FN(Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,RIY,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-May-2018 22:13:52

t2 = sqrt(4.1e1);
t3 = sqrt(2.0);
t4 = pi.*(1.0./4.0);
V = rIy.*5.31702e2-cos(q1+q2+theta).*8.9271-cos(q4+q5+theta).*8.9271-cos(q7+q8+theta).*7.725375-cos(q9+q10+theta).*7.725375-cos(q1+theta).*1.91295e1-cos(q4+theta).*1.91295e1-cos(q7+theta).*1.1158875e1-cos(q9+theta).*1.1158875e1+cos(theta).*1.3326885e2-t2.*cos(q1+q2+q3+theta-8.960553845713439e-1).*1.962e-1-t2.*cos(q4+q5+q6+theta-8.960553845713439e-1).*1.962e-1-t3.*cos(q1+q2+q3+t4+theta).*7.848e-1-t3.*cos(q4+q5+q6+t4+theta).*7.848e-1;
