function vA = vA_fn(q1,q2,q3,q1dot,q2dot,q3dot,rIxdot,rIydot,thetadot,theta)
%VA_FN
%    VA = VA_FN(Q1,Q2,Q3,Q1DOT,Q2DOT,Q3DOT,RIXDOT,RIYDOT,THETADOT,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Apr-2018 15:37:15

t2 = pi.*(1.0./2.0);
t3 = q1+t2+theta;
t4 = sin(t3);
t5 = t4.*(1.3e1./4.0e1);
t6 = q1+q2+t2+theta;
t7 = sin(t6);
t8 = t7.*(1.3e1./4.0e1);
t9 = sqrt(4.1e1);
t10 = q1+q2+q3+t2+theta-8.960553845713439e-1;
t11 = sin(t10);
t12 = t9.*t11.*(1.0./4.0e1);
t13 = t5+t8+t12;
t14 = cos(t3);
t15 = t14.*(1.3e1./4.0e1);
t16 = cos(t6);
t17 = t16.*(1.3e1./4.0e1);
t18 = cos(t10);
t19 = t9.*t18.*(1.0./4.0e1);
t20 = t15+t17+t19;
vA = [rIxdot-q2dot.*(t8+t12)-q1dot.*t13-t13.*thetadot-q3dot.*t9.*t11.*(1.0./4.0e1);rIydot-q2dot.*(t17+t19)-q1dot.*t20-t20.*thetadot-q3dot.*t9.*t18.*(1.0./4.0e1)];
