function vB = vB_fn(q1,q2,q3,q1dot,q2dot,q3dot,rIxdot,rIydot,thetadot,theta)
%VB_FN
%    VB = VB_FN(Q1,Q2,Q3,Q1DOT,Q2DOT,Q3DOT,RIXDOT,RIYDOT,THETADOT,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Apr-2018 12:50:53

t2 = pi.*(1.0./2.0);
t3 = q1+t2+theta;
t4 = sin(t3);
t5 = t4.*(1.3e1./4.0e1);
t6 = q1+q2+t2+theta;
t7 = sin(t6);
t8 = t7.*(1.3e1./4.0e1);
t9 = sqrt(2.0);
t14 = pi.*(5.0./4.0);
t10 = q1+q2+q3-t14+theta;
t11 = sin(t10);
t12 = t9.*t11.*(1.0./1.0e1);
t13 = t5+t8+t12;
t15 = cos(t3);
t16 = t15.*(1.3e1./4.0e1);
t17 = cos(t6);
t18 = t17.*(1.3e1./4.0e1);
t19 = cos(t10);
t20 = t9.*t19.*(1.0./1.0e1);
t21 = t16+t18+t20;
vB = [rIxdot-q2dot.*(t8+t12)-q1dot.*t13-t13.*thetadot-q3dot.*t9.*t11.*(1.0./1.0e1);rIydot-q2dot.*(t18+t20)-q1dot.*t21-t21.*thetadot-q3dot.*t9.*t19.*(1.0./1.0e1)];
