function vC = vC_fn(q4,q5,q6,q4dot,q5dot,q6dot,rIxdot,rIydot,thetadot,theta)
%VC_FN
%    VC = VC_FN(Q4,Q5,Q6,Q4DOT,Q5DOT,Q6DOT,RIXDOT,RIYDOT,THETADOT,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Apr-2018 12:50:53

t2 = pi.*(1.0./2.0);
t3 = q4+t2+theta;
t4 = sin(t3);
t5 = t4.*(1.3e1./4.0e1);
t6 = q4+q5+t2+theta;
t7 = sin(t6);
t8 = t7.*(1.3e1./4.0e1);
t9 = sqrt(4.1e1);
t10 = q4+q5+q6+t2+theta-8.960553845713439e-1;
t11 = sin(t10);
t12 = t9.*t11.*(1.0./4.0e1);
t13 = t5+t8+t12;
t14 = cos(t3);
t15 = t14.*(1.3e1./4.0e1);
t16 = cos(t6);
t17 = t16.*(1.3e1./4.0e1);
t18 = cos(t10);
t19 = t9.*t18.*(1.0./4.0e1);
t20 = t15+t17+t19;
vC = [rIxdot-q5dot.*(t8+t12)-q4dot.*t13-t13.*thetadot-q6dot.*t9.*t11.*(1.0./4.0e1);rIydot-q5dot.*(t17+t19)-q4dot.*t20-t20.*thetadot-q6dot.*t9.*t18.*(1.0./4.0e1)];
