function vD = vD_fn(q4,q5,q6,q4dot,q5dot,q6dot,rIxdot,rIydot,thetadot,theta)
%VD_FN
%    VD = VD_FN(Q4,Q5,Q6,Q4DOT,Q5DOT,Q6DOT,RIXDOT,RIYDOT,THETADOT,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Apr-2018 15:37:16

t2 = pi.*(1.0./2.0);
t3 = q4+t2+theta;
t4 = sin(t3);
t5 = t4.*(1.3e1./4.0e1);
t6 = q4+q5+t2+theta;
t7 = sin(t6);
t8 = t7.*(1.3e1./4.0e1);
t9 = sqrt(2.0);
t10 = pi.*(3.0./4.0);
t11 = q4+q5+q6+t10+theta;
t12 = sin(t11);
t13 = t9.*t12.*(1.0./1.0e1);
t14 = t5+t8+t13;
t15 = cos(t3);
t16 = t15.*(1.3e1./4.0e1);
t17 = cos(t6);
t18 = t17.*(1.3e1./4.0e1);
t19 = cos(t11);
t20 = t9.*t19.*(1.0./1.0e1);
t21 = t16+t18+t20;
vD = [rIxdot-q5dot.*(t8+t13)-q4dot.*t14-t14.*thetadot-q6dot.*t9.*t12.*(1.0./1.0e1);rIydot-q5dot.*(t18+t20)-q4dot.*t21-t21.*thetadot-q6dot.*t9.*t19.*(1.0./1.0e1)];
