function vG = vG_fn(q1,q2,q1dot,q2dot,rIxdot,rIydot,thetadot,theta)
%VG_FN
%    VG = VG_FN(Q1,Q2,Q1DOT,Q2DOT,RIXDOT,RIYDOT,THETADOT,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Apr-2018 12:50:54

t2 = pi.*(1.0./2.0);
t3 = q1+t2+theta;
t4 = sin(t3);
t5 = t4.*(1.3e1./4.0e1);
t6 = q1+q2+t2+theta;
t7 = sin(t6);
t8 = t7.*(1.3e1./4.0e1);
t9 = t5+t8;
t10 = cos(t3);
t11 = t10.*(1.3e1./4.0e1);
t12 = cos(t6);
t13 = t12.*(1.3e1./4.0e1);
t14 = t11+t13;
vG = [rIxdot-q2dot.*t7.*(1.3e1./4.0e1)-q1dot.*t9-t9.*thetadot;rIydot-q2dot.*t12.*(1.3e1./4.0e1)-q1dot.*t14-t14.*thetadot];
