function vJ = vJ_fn(q4,q5,q4dot,q5dot,rIxdot,rIydot,thetadot,theta)
%VJ_FN
%    VJ = VJ_FN(Q4,Q5,Q4DOT,Q5DOT,RIXDOT,RIYDOT,THETADOT,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Apr-2018 15:37:17

t2 = pi.*(1.0./2.0);
t3 = q4+t2+theta;
t4 = sin(t3);
t5 = t4.*(1.3e1./4.0e1);
t6 = q4+q5+t2+theta;
t7 = sin(t6);
t8 = t7.*(1.3e1./4.0e1);
t9 = t5+t8;
t10 = cos(t3);
t11 = t10.*(1.3e1./4.0e1);
t12 = cos(t6);
t13 = t12.*(1.3e1./4.0e1);
t14 = t11+t13;
vJ = [rIxdot-q5dot.*t7.*(1.3e1./4.0e1)-q4dot.*t9-t9.*thetadot;rIydot-q5dot.*t12.*(1.3e1./4.0e1)-q4dot.*t14-t14.*thetadot];
