function vK = vK_fn(q4,q4dot,rIxdot,rIydot,thetadot,theta)
%VK_FN
%    VK = VK_FN(Q4,Q4DOT,RIXDOT,RIYDOT,THETADOT,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    25-Apr-2018 15:37:17

t2 = pi.*(1.0./2.0);
t3 = q4+t2+theta;
t4 = sin(t3);
t5 = cos(t3);
vK = [rIxdot-q4dot.*t4.*(1.3e1./4.0e1)-t4.*thetadot.*(1.3e1./4.0e1);rIydot-q4dot.*t5.*(1.3e1./4.0e1)-t5.*thetadot.*(1.3e1./4.0e1)];
