function vL = vL_fn(rIxdot,rIydot,thetadot,theta)
%VL_FN
%    VL = VL_FN(RIXDOT,RIYDOT,THETADOT,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Apr-2018 12:50:55

t2 = theta-pi.*(1.0./2.0);
vL = [rIxdot-thetadot.*sin(t2).*(1.1e1./2.0e1);rIydot-thetadot.*cos(t2).*(1.1e1./2.0e1)];
