function vM = vM_fn(q7,q7dot,rIxdot,rIydot,thetadot,theta)
%VM_FN
%    VM = VM_FN(Q7,Q7DOT,RIXDOT,RIYDOT,THETADOT,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Apr-2018 12:50:55

t2 = pi.*(1.0./2.0);
t3 = q7+t2+theta;
t4 = sin(t3);
t5 = cos(t3);
t6 = -t2+theta;
vM = [rIxdot-q7dot.*t4.*(1.0./4.0)-thetadot.*(t4.*(1.0./4.0)+sin(t6).*(1.1e1./2.0e1));rIydot-thetadot.*(t5.*(1.0./4.0)+cos(t6).*(1.1e1./2.0e1))-q7dot.*t5.*(1.0./4.0)];
