function vT = vT_fn(rIxdot,rIydot,thetadot,theta)
%VT_FN
%    VT = VT_FN(RIXDOT,RIYDOT,THETADOT,THETA)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    26-Apr-2018 12:50:55

t2 = theta-pi.*(1.0./2.0);
vT = [rIxdot-thetadot.*sin(t2).*(7.0./1.0e1);rIydot-thetadot.*cos(t2).*(7.0./1.0e1)];
